modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="tacz_mcs2_gunpack_projecte_compat"
version="1.0.2"
displayName="TacZ MCS2 GunPack ProjectE Compat"
authors="Rainbow-SPY"
description='''
EMC pricing compatibility for ProjectE of the gun pack MCS2 for Timeless and Classics Zero
对 TaCZ 的 MCS2 枪包 的 等价交换重置版 的 EMC 定价兼容
'''

[[dependencies.tacz_mcs2_gunpack_projecte_compat]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.tacz_mcs2_gunpack_projecte_compat]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.tacz_mcs2_gunpack_projecte_compat]]
modId="projecte"
type="required"
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tacz_mcs2_gunpack_projecte_compat]]
modId="tacz"
type="required"
versionRange="[1.1.8,)"
ordering="AFTER"
side="BOTH"
